# Generated by Django 4.2.2 on 2023-07-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eid',
            new_name='aid',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
